Ext.define("AliveTracker.default.Constants",{

    statics: {
        PROFILE_LOGO_URL: '/resources/icons/user.png',
        REPORTS_CUSTOM_DATERANGE_OPTION: 1,
        REPORTS_CUSTOM_DATERANGE_DESCRIPTION: 'Customized',
        REPORTS_LAST_DAY_DATERANGE_OPTION: 2,
        REPORTS_LAST_DAY_DATERANGE_DESCRIPTION: 'Last day',
        REPORTS_LAST_SEVEN_DAYS_DATERANGE_OPTION: 3,
        REPORTS_LAST_SEVEN_DAYS_DATERANGE_DESCRIPTION: 'Last 7 days',
        REPORTS_LAST_TWO_WEEKS_DATERANGE_OPTION: 4,
        REPORTS_LAST_TWO_WEEKS_DATERANGE_DESCRIPTION: 'Last 2 weeks',
        REPORTS_LAST_MONTH_DATERANGE_OPTION: 5,
        REPORTS_LAST_MONTH_DATERANGE_DESCRIPTION: 'Last month'

    }

});